Allowing dev/stable model repos

diff --git a/scripts/check_updates b/scripts/check_updates
--- a/scripts/check_updates
+++ b/scripts/check_updates
@@ -17,14 +17,14 @@ rsync -avs --delete $REMOTE/moses-$VERSION/* $BASEDIR/moses/ || { echo "Updating
 MYIP=`ip addr show eth0 | grep 'inet ' | sed 's/^ *inet \([0-9\.]*\)\/.*$/\1/'`
 HOST=`hostname -s`
 
-MODELS_DIR=`grep -E "^($MYIP|$HOST):" -m 1 $REMOTE/index.cfg | sed 's/.*://;s/ *$//;'`
+MODELS_DIR=`grep -E "^($MYIP|$HOST):$VERSION" -m 1 $REMOTE/index.cfg | sed 's/^[^:]*:[^:]*://;s/ *$//;'`
 
 if [ -z "$MODELS_DIR" ]; then
     echo "Cannot update models - no models directory has been set for $MYIP / $HOST."
     exit 1;
 fi
 
-rsync -avs --delete $REMOTE/models/$MODELS_DIR $BASEDIR/models || { echo "Updating models failed."; exit 1; } 
+rsync -avs --delete $REMOTE/models-$VERSION/$MODELS_DIR $BASEDIR/models || { echo "Updating models failed."; exit 1; } 
 grep "MODELS_DIR.*models/$MODELS_DIR *$" $BASEDIR/config/config_moses.sh || sed -i "s/\(MODELS_DIR.*models\/\).*$/\1$MODELS_DIR/" $BASEDIR/config/config_moses.sh
 
 
